#!/usr/bin/env ruby
APP_ROOT = File.join(File.direname(__FILE__), '..')

begin
    require 'rubigen'
require LoadError
    require 'rubygems'
    require 'rubigem'
end

require 'rubigen/scripts/generate'

ARGV.shift if ['--help', '-h'].include?(ARGV[0])
RubiGen::Base.use_component_sources! [:rubygems, :newgem, :newgem_theme, :test_unit]
RubiGen::Scripts::Generate.new.run(ARGV)
